### ISSUE TITLE
[QUESTION] Can it work with esp32?

### ISSUE THREAD

**Issue by zekageri** [Fredi/ArduinoIRC#5]
I want to use it with an esp32. Do i have to do some tweaking for that?

**Comment by zekageri** [comment]
### Sounds good doesn't work.

```
    #include <Arduino.h>
    #include <ETH.h>

    #define IRC_SERVER   "irc.rizon.net"
    #define IRC_PORT     6667
    #define IRC_NICKNAME "Hitec_Test"
    #define IRC_USER     "Hitec_Test"

    ESP32Ethernet ethernet;
    IRCClient client(IRC_SERVER, IRC_PORT, ethernet);   // <-- Compiler complaining for ethernet

   void setup(){
     Serial.begin(115200);
     ethernet.begin();
   }
  
   void loop(){
   }
```

[Ethernet.h](https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/include/lwip/netif/ethernet.h)
[Some ETH Example](https://github.com/espressif/arduinoesp32/blob/master/libraries/WiFi/examples/ETH_LAN8720/ETH_LAN8720.ino)

I will try it with wificlient on esp32 or 8266 soon. :/

**Comment by fredimachado** [comment]
Hi @zekageri,

Probably because this ESP32Ethernet type doesn't derive from Client. You can find Arduino's ethernet Client here: https://github.com/lstoll/arduino-libraries/blob/master/Ethernet/Client.cpp
So it won't work out-of-the-box in this case without code change.
I'll probably buy an ESP32 in the future (and update this library), but I can't promise anything.
If you fix it, please consider creating a Pull request so we can update this library :)

Cheers,
Fredi

**Comment by zekageri** [comment]
Thanks for your answer.i will. ^^
